import turtle
while True:
    myTurtle = turtle.Turtle()
    myTurtle.penup()
    myTurtle.setx(200)
    myTurtle.sety(200)
    myTurtle.pendown()
    myTurtle.pencolor("blue")
    myTurtle.forward(100)
    myTurtle.right(90)
    myTurtle.forward(100)
    myTurtle.right(90)
    myTurtle.forward(100)
    myTurtle.right(90)
    myTurtle.forward(100)
    #myTurtle.penup()
    #myTurtle.pendown()
    #myTurtle.pencolor("blue")
    #myTurtle.setx()
    #myTurtle.sety()
    #myTurtle.circle()
    #myTurtle.backwards()
